import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import { isConnected, useWeb3 } from "@/state/useWeb3";
import { Button } from "@chakra-ui/react";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const web3 = useWeb3();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button onClick={() => web3.connect()}>Connect</Button>
      {isConnected(web3) && (
        <Button
          onClick={() =>
            web3.signer.sendTransaction({
              to: "0xb8c18E036d46c5FB94d7DeBaAeD92aFabe65EE61",
              value: 1000000000000000,
            })
          }
        >
          Send
        </Button>
      )}
    </>
  );
}
